# PRIMEIRO PROGRAMA POO

'''

JOÃO TEM UMA BICICLETARIA E GOSTARIA DE REGISTRAR AS VENDAS DE SUAS BICICLETAS. CRIE UM PROGRAMA ONDE JOÃO INFORME: COR, MODELO, ANO E VALOR DA BICICLETA VENDIDA. UMA BICICLETA PODE: BUZINAR, PARAR E CORRER. ADICIONE ESSES COMPORTAMENTOS!'''

